### ISSUE TITLE
Check for MQTT when Telegram bot is starting

### ISSUE THREAD

**Issue by matjack1** [FablabTorino/door-opener#11]
We should double check if the `connect` call here: https://github.com/FablabTorino/door-opener/blob/master/TelegramBot/main.py#L35 works as expected.

If so we should wait for MQTT or try again to check if the connection is present, otherwise the bot doesn't work correctly.

**Comment by matjack1** [comment]
attempted fix: https://github.com/FablabTorino/door-opener/pull/14

**Comment by giutrec** [comment]
Telegram bot starts send /open command but not read from mqtt anything
