### ISSUE TITLE
Esp-rfid: implementazione timezone per non dover cambiare il fuso orario tra ora solare e legale

### ISSUE THREAD

**Issue by giutrec** [FablabTorino/door-opener#33]
Qui un tentativo non funzionante https://github.com/giutrec/esp-rfid/tree/timezones

va in conflitto con l'implementazione dell'ntp di esp-rfid che è legato con la libreria timezone

**Comment by giutrec** [comment]
basato si questo esempio
https://github.com/esp8266/Arduino/blob/master/libraries/esp8266/examples/NTP-TZ-DST/NTP-TZ-DST.ino

**Comment by matjack1** [comment]
https://github.com/esp8266/Arduino/issues/7353
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/system_time.html
https://github.com/SensorsIot/NTP-time-for-ESP8266-and-ESP32

**Comment by matjack1** [comment]
direi che è fatto!
