### ISSUE TITLE
esp-rfid: problema riconnessione mqtt

### ISSUE THREAD

**Issue by giutrec** [FablabTorino/door-opener#36]
Per qualche motivo quando il device si disconnette dalla rete wifi e resta offline per parecchio tempo alla riconnessione non riesce a tirare su il client mqtt.

Possibili soluzioni:
- forzare disconnessione client mqtt alla disconnessione del wifi (ad oggi lo fa con un timeout)
- forzare inizializzazione del client mqtt alla riconnessione del wifi

**Comment by giutrec** [comment]
credo sia un problema nel ticker.h

**Comment by matjack1** [comment]
> forzare inizializzazione del client mqtt alla riconnessione del wifi

questo c'è già, quando fa `connectSTA` forza la connessione MQTT e questa funzione è quella chiamata dalla nostra riconnessione ogni 5 minuti.

> forzare disconnessione client mqtt alla disconnessione del wifi (ad oggi lo fa con un timeout)

questo invece potrebbe essere furbo da tentare!

Per quanto riguarda i ticker non so, dovrebbe partire solo quando il wifi è connesso, altrimenti fa il detach. Magari non ho capito bene come si usa però, non so :)

**Comment by giutrec** [comment]
Si il problema di base è che dopo un tot che l'esp resta senza wifi, si riconnette alla rete ma non tira più su il client mqtt, a random poi lo tirasu quando si fa il login su interfaccia web ma è molto randomica come cosa, bisogna trovare il modo per forzare il tentativo di riconnessione mqtt ogni volta che si riconnette al wifi ed ovviamente forzare la disconnessione mqtt ogni volta che il wifi va offline. Forse potremmo risolvere, forse :D

**Comment by matjack1** [comment]
OK, ho provato a forzare la disconnessione da qua: https://github.com/esprfid/esp-rfid/tree/mqtt-disconnect

Anche questo è ancora da testare.

**Comment by matjack1** [comment]
Mi sembra che qua siamo a posto
