### ISSUE TITLE
esp-rfid: analisi funzionamento wifi

### ISSUE THREAD

**Issue by giutrec** [FablabTorino/door-opener#37]
Ad oggi il sistema fa un tentativo di riconnessione ogni 15 minuti, però mi sono accorto che a prescindere dal tentativo di riconnessione identifica immediatamente quando si attiva il wifi

**Comment by matjack1** [comment]
sì @giutrec ci sono due meccanismi di riconnessione. In automatico la libreria wifi di esp8266 prova a fare il reconnect, che sarebbe buono, ma dopo un po' smette, penso perché va in sleep (o ha dei timeout, non ho capito).

Quindi per questo abbiamo dovuto aggiungere noi un pezzo che manualmente prova a riconnettersi. Ora riprova ogni 5 minuti.

Chiudo qua ma riapri pure se serve altro.
