### ISSUE TITLE
URGENTE:  Malfunzionamento livelli di accesso

### ISSUE THREAD

**Issue by giutrec** [FablabTorino/door-opener#38]
Qualcosa non funziona [QUI](https://github.com/esprfid/esp-rfid/blob/dev/src/rfid.esp#L305) non riesce a fare la comparazione tra l'ora attuale e le fasce orarie inoltre manca un else [QUI](https://github.com/esprfid/esp-rfid/blob/dev/src/rfid.esp#L312) per far funzionare correttamente la condizione, ma facendola funzionare correttamente siccome il [bool](https://github.com/esprfid/esp-rfid/blob/dev/src/rfid.esp#L305)  non da mai risposta "true" non apre mai a nessuno.

Credo sia dovuto al arduio json ma non ne sono sicuro!

**Comment by matjack1** [comment]
Stasera riesco a testare, ma nel frattempo se vuoi provare questo: https://github.com/esprfid/esp-rfid/tree/fix-openinghours forse fixa!

**Comment by giutrec** [comment]
problema risolto chiudo
