### ISSUE TITLE
REBUG! Accesso seconda porta

### ISSUE THREAD

**Issue by giutrec** [FablabTorino/door-opener#39]
Abbiamo nuovamente il bug che non fa aprire la seconda porta (nei casi in cui l'esp gestisca più di una porta)
la riga incriminata nel rfid.esp + questa, funzionava ma dopo l'aggiornamento dell'arduino json si è rispaccata
bool isRelayActive = json["acctype" + String(currentRelay + 1)] == ACCESS_GRANTED;

Promemoria per smartellamenti

**Comment by giutrec** [comment]
Ciao, ho fatto la prova al fablab, funzionava ne sono sicuro, ma ora non funge più ho provato anche così 
bool isRelayActive = json["acctype" + String(currentRelay + '1')] == ACCESS_GRANTED;

ma non funziona

Proverò a tornare indietro

**Comment by matjack1** [comment]
@giutrec ottimo, ma fallo anche nel repo ufficiale!
